name: Build Image Step 2
on:
  push:
    branches:
      - main  
  workflow_run:
    workflows: ["Build Image Step 1"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  Build-Base-Image-Step2:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: "Optimize Disk Space"
          uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.0"
          with:
            operate_sudo: "True"
            general_include: ".+"
            docker_include: ".+"
            docker_prune: "True"
            docker_clean: "True"
            apt_prune: "True"
            apt_clean: "True"
            homebrew_prune: "True"
            homebrew_clean: "True"
            npm_prune: "True"
            npm_clean: "True"
            os_swap: "True"

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker
          uses: docker/setup-docker-action@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - run: sudo npm install -g @devcontainers/cli

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Base Image
          run: |
            docker pull sunshinecloud007/sunshinecloud-universal-desktop:build-layer
            df -h

        - name: Merge Docker Image
          run: |
            export src_image_name=sunshinecloud007/sunshinecloud-universal-desktop:build-layer
            export docker_tmp_name=temp1
            echo "Creating temporary container from image..."
            docker create -it -P --name $docker_tmp_name $src_image_name
            echo "Exporting container to tar..."
            docker export $docker_tmp_name -o $docker_tmp_name.tar
            echo "Removing Raw container..."
            docker rm $docker_tmp_name
            echo "Removing Raw image..."
            docker rmi $src_image_name
            echo "Importing tar to image..."
            docker import $docker_tmp_name.tar $src_image_name
            echo "Creating temporary container from image..."
            docker create -it -P --name $docker_tmp_name $src_image_name bash
            echo "Committing container with new ENTRYPOINT and CMD..."
            docker commit \
              --change='USER matrix0523' \
              --change='ENTRYPOINT ["/bin/bash", "-c"]' \
              --change='CMD ["sudo /usr/local/share/docker-init.sh bash -c '\''sudo service supervisor start && sudo service dbus restart && sudo service xrdp start && bash'\''"]' \
              $docker_tmp_name $src_image_name
            rm $docker_tmp_name.tar
            docker images $src_image_name
            docker tag $src_image_name sunshinecloud007/sunshinecloud-universal-desktop:base

        - name: Push Docker Image
          run: |
            docker push sunshinecloud007/sunshinecloud-universal-desktop:base