name: Build Image Step 1
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allow manual triggering

jobs:
  Build-Base-Image-Step1:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: "Optimize Disk Space"
          uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.0"
          with:
            operate_sudo: "True"
            general_include: ".+"
            docker_include: ".+"
            docker_prune: "True"
            docker_clean: "True"
            apt_prune: "True"
            apt_clean: "True"
            homebrew_prune: "True"
            homebrew_clean: "True"
            npm_prune: "True"
            npm_clean: "True"
            os_swap: "True"

        - name: Remove / Purge Docker 
          run: |
            sudo apt purge -y docker* 

        - name: Set up Docker
          uses: docker/setup-docker-action@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3


        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - run: sudo npm install -g @devcontainers/cli

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        # - name: Build Image
        #   run: |
        #     # export image-name=sunshinecloud-java-devcontainers
        #     # export image_version=latest
        #     devcontainer build --workspace-folder . --image-name 
        #     df -h

        # - name: Push Docker Image
        #   run: |
        #     docker push sunshinecloud007/sunshinecloud-universal-desktop:build-layer

        - name: Build Image
          uses: devcontainers/ci@v0.3
          with:
            imageName: sunshinecloud007/sunshinecloud-universal-desktop
            imageTag: base
            noCache: true
            push: always

        - name: Print Disk Usage
          run: |
            df -h   
