name: Stable-Diffusion-WebUI-Desktop
on:
  # push:
  #   branches:
  #     - main  
  workflow_run:
    workflows: ["Compress Step 2 Image"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  Build-SDWEBUI-Desktop:
    runs-on: self-hosted
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # - name: "Optimize Disk Space"
        #   uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.0"
        #   with:
        #     operate_sudo: "True"
        #     general_include: ".+"
        #     docker_include: ".+"
        #     docker_prune: "True"
        #     docker_clean: "True"
        #     apt_prune: "True"
        #     apt_clean: "True"
        #     homebrew_prune: "True"
        #     homebrew_clean: "True"
        #     npm_prune: "True"
        #     npm_clean: "True"
        #     os_swap: "True"

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker
          uses: docker/setup-docker-action@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - run: sudo npm install -g @devcontainers/cli

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./Stable-Diffusion-WebUI-Desktop/
            platforms: linux/amd64
            push: true
            load: false
            tags: |
              sunshinecloud007/sunshinecloud-stable-diffusion-webui-desktop:latest
              sunshinecloud007/sunshinecloud-stable-diffusion-webui-desktop:latest-${{ github.sha }}

        - name: Print Disk Usage
          run: |
            df -h  